name: REsk
channels:
  - conda-forge
dependencies:
  - scipy
  - numpy
  - pandas
  - scikit-learn>=0.20
  - matplotlib
  - seaborn
  - jupyter
  - geopandas
  - json
  - bokeh

  # Extra processing packages
  - lightgbm
  - catboost
  - xgboost
  - category_encoders  
  - pip:
      - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/master
      - googledrivedownloader
